//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Novyjj_proekt_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Перечень товаров.
    /// </summary>
    [Caption("Перечень товаров")]
    [TrimmedStringStorage(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПереченьТоваровE", new string[] {
            "Количество as \'Количество\'",
            "Товары as \'Товары\'",
            "Товары.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Товары.Наименование"})]
    [MasterViewDefineAttribute("ПереченьТоваровE", "Товары", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class ПереченьТоваров : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private IIS.Novyjj_proekt_2.Товары fТовары;
        
        private IIS.Novyjj_proekt_2.ПриходДенег fПриходДенег;
        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ПереченьТоваров.Количество CustomAttributes)

        // *** End programmer edit section *** (ПереченьТоваров.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ПереченьТоваров.Количество Get start)

                // *** End programmer edit section *** (ПереченьТоваров.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ПереченьТоваров.Количество Get end)

                // *** End programmer edit section *** (ПереченьТоваров.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПереченьТоваров.Количество Set start)

                // *** End programmer edit section *** (ПереченьТоваров.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ПереченьТоваров.Количество Set end)

                // *** End programmer edit section *** (ПереченьТоваров.Количество Set end)
            }
        }
        
        /// <summary>
        /// Перечень товаров.
        /// </summary>
        [PropertyStorage(new string[] {
                "Товары"})]
        [NotNull()]
        public virtual IIS.Novyjj_proekt_2.Товары Товары
        {
            get
            {
                IIS.Novyjj_proekt_2.Товары result = this.fТовары;
                return result;
            }
            set
            {
                this.fТовары = value;
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Novyjj_proekt_2.ПриходДенег.
        /// </summary>
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ПриходДенег"})]
        public virtual IIS.Novyjj_proekt_2.ПриходДенег ПриходДенег
        {
            get
            {
                IIS.Novyjj_proekt_2.ПриходДенег result = this.fПриходДенег;
                return result;
            }
            set
            {
                this.fПриходДенег = value;
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПереченьТоваровE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПереченьТоваровE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПереченьТоваровE", typeof(IIS.Novyjj_proekt_2.ПереченьТоваров));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ПереченьТоваров.
    /// </summary>
    public class DetailArrayOfПереченьТоваров : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Novyjj_proekt_2.DetailArrayOfПереченьТоваров members)

        // *** End programmer edit section *** (IIS.Novyjj_proekt_2.DetailArrayOfПереченьТоваров members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ПереченьТоваров by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ПереченьТоваров.
        /// </summary>
        public DetailArrayOfПереченьТоваров(IIS.Novyjj_proekt_2.ПриходДенег fПриходДенег) : 
                base(typeof(ПереченьТоваров), ((ICSSoft.STORMNET.DataObject)(fПриходДенег)))
        {
        }
        
        public IIS.Novyjj_proekt_2.ПереченьТоваров this[int index]
        {
            get
            {
                return ((IIS.Novyjj_proekt_2.ПереченьТоваров)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Novyjj_proekt_2.ПереченьТоваров dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
