//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Novyjj_proekt_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Приход денег.
    /// </summary>
    [Caption("Приход денег")]
    [TrimmedStringStorage(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПриходДенегE", new string[] {
            "ID as \'ID\'",
            "Дата as \'Дата\'",
            "Финансисты as \'Финансисты\'",
            "Финансисты.ФИО as \'ФИО Финансиста\'",
            "Клиенты as \'Клиенты\'",
            "Клиенты.ФИО as \'ФИО Клиента\'",
            "РасходПриход as \'Расход/приход\'",
            "Тип as \'Тип\'",
            "Сумма as \'Сумма\'"}, Hidden=new string[] {
            "Финансисты.ФИО",
            "Клиенты.ФИО"})]
    [AssociatedDetailViewAttribute("ПриходДенегE", "ПереченьТоваров", "ПереченьТоваровE", true, "", "Перечень товаров", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("ПриходДенегE", "ПереченьУслуг", "ПереченьУслугE", true, "", "Перечень услуг", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ПриходДенегE", "Финансисты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ПриходДенегE", "Клиенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ПриходДенегL", new string[] {
            "ID as \'ID\'",
            "Дата as \'Дата\'",
            "РасходПриход as \'Расход приход\'",
            "Тип as \'Тип\'",
            "Сумма as \'Сумма\'",
            "Финансисты.ФИО as \'ФИО\'",
            "Клиенты.ФИО as \'ФИО\'"})]
    public class ПриходДенег : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private System.DateTime fДата;
        
        private IIS.Novyjj_proekt_2.РасходПриход fРасходПриход;
        
        private IIS.Novyjj_proekt_2.Тип fТип;
        
        private double fСумма;
        
        private IIS.Novyjj_proekt_2.Финансисты fФинансисты;
        
        private IIS.Novyjj_proekt_2.Клиенты fКлиенты;
        
        private IIS.Novyjj_proekt_2.DetailArrayOfПереченьТоваров fПереченьТоваров;
        
        private IIS.Novyjj_proekt_2.DetailArrayOfПереченьУслуг fПереченьУслуг;
        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (ПриходДенег.ID CustomAttributes)

        // *** End programmer edit section *** (ПриходДенег.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (ПриходДенег.ID Get start)

                // *** End programmer edit section *** (ПриходДенег.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (ПриходДенег.ID Get end)

                // *** End programmer edit section *** (ПриходДенег.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходДенег.ID Set start)

                // *** End programmer edit section *** (ПриходДенег.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (ПриходДенег.ID Set end)

                // *** End programmer edit section *** (ПриходДенег.ID Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ПриходДенег.Дата CustomAttributes)

        // *** End programmer edit section *** (ПриходДенег.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ПриходДенег.Дата Get start)

                // *** End programmer edit section *** (ПриходДенег.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ПриходДенег.Дата Get end)

                // *** End programmer edit section *** (ПриходДенег.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходДенег.Дата Set start)

                // *** End programmer edit section *** (ПриходДенег.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ПриходДенег.Дата Set end)

                // *** End programmer edit section *** (ПриходДенег.Дата Set end)
            }
        }
        
        /// <summary>
        /// РасходПриход.
        /// </summary>
        // *** Start programmer edit section *** (ПриходДенег.РасходПриход CustomAttributes)

        // *** End programmer edit section *** (ПриходДенег.РасходПриход CustomAttributes)
        public virtual IIS.Novyjj_proekt_2.РасходПриход РасходПриход
        {
            get
            {
                // *** Start programmer edit section *** (ПриходДенег.РасходПриход Get start)

                // *** End programmer edit section *** (ПриходДенег.РасходПриход Get start)
                IIS.Novyjj_proekt_2.РасходПриход result = this.fРасходПриход;
                // *** Start programmer edit section *** (ПриходДенег.РасходПриход Get end)

                // *** End programmer edit section *** (ПриходДенег.РасходПриход Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходДенег.РасходПриход Set start)

                // *** End programmer edit section *** (ПриходДенег.РасходПриход Set start)
                this.fРасходПриход = value;
                // *** Start programmer edit section *** (ПриходДенег.РасходПриход Set end)

                // *** End programmer edit section *** (ПриходДенег.РасходПриход Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (ПриходДенег.Сумма CustomAttributes)

        // *** End programmer edit section *** (ПриходДенег.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (ПриходДенег.Сумма Get start)

                // *** End programmer edit section *** (ПриходДенег.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (ПриходДенег.Сумма Get end)

                // *** End programmer edit section *** (ПриходДенег.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходДенег.Сумма Set start)

                // *** End programmer edit section *** (ПриходДенег.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (ПриходДенег.Сумма Set end)

                // *** End programmer edit section *** (ПриходДенег.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (ПриходДенег.Тип CustomAttributes)

        // *** End programmer edit section *** (ПриходДенег.Тип CustomAttributes)
        public virtual IIS.Novyjj_proekt_2.Тип Тип
        {
            get
            {
                // *** Start programmer edit section *** (ПриходДенег.Тип Get start)

                // *** End programmer edit section *** (ПриходДенег.Тип Get start)
                IIS.Novyjj_proekt_2.Тип result = this.fТип;
                // *** Start programmer edit section *** (ПриходДенег.Тип Get end)

                // *** End programmer edit section *** (ПриходДенег.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриходДенег.Тип Set start)

                // *** End programmer edit section *** (ПриходДенег.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (ПриходДенег.Тип Set end)

                // *** End programmer edit section *** (ПриходДенег.Тип Set end)
            }
        }
        
        /// <summary>
        /// Приход денег.
        /// </summary>
        [PropertyStorage(new string[] {
                "Клиенты"})]
        [NotNull()]
        public virtual IIS.Novyjj_proekt_2.Клиенты Клиенты
        {
            get
            {
                IIS.Novyjj_proekt_2.Клиенты result = this.fКлиенты;
                return result;
            }
            set
            {
                this.fКлиенты = value;
            }
        }
        
        /// <summary>
        /// Приход денег.
        /// </summary>
        [PropertyStorage(new string[] {
                "Финансисты"})]
        [NotNull()]
        public virtual IIS.Novyjj_proekt_2.Финансисты Финансисты
        {
            get
            {
                IIS.Novyjj_proekt_2.Финансисты result = this.fФинансисты;
                return result;
            }
            set
            {
                this.fФинансисты = value;
            }
        }
        
        /// <summary>
        /// Приход денег.
        /// </summary>
        public virtual IIS.Novyjj_proekt_2.DetailArrayOfПереченьТоваров ПереченьТоваров
        {
            get
            {
                if ((this.fПереченьТоваров == null))
                {
                    this.fПереченьТоваров = new IIS.Novyjj_proekt_2.DetailArrayOfПереченьТоваров(this);
                }
                IIS.Novyjj_proekt_2.DetailArrayOfПереченьТоваров result = this.fПереченьТоваров;
                return result;
            }
            set
            {
                this.fПереченьТоваров = value;
            }
        }
        
        /// <summary>
        /// Приход денег.
        /// </summary>
        public virtual IIS.Novyjj_proekt_2.DetailArrayOfПереченьУслуг ПереченьУслуг
        {
            get
            {
                if ((this.fПереченьУслуг == null))
                {
                    this.fПереченьУслуг = new IIS.Novyjj_proekt_2.DetailArrayOfПереченьУслуг(this);
                }
                IIS.Novyjj_proekt_2.DetailArrayOfПереченьУслуг result = this.fПереченьУслуг;
                return result;
            }
            set
            {
                this.fПереченьУслуг = value;
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПриходДенегE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриходДенегE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриходДенегE", typeof(IIS.Novyjj_proekt_2.ПриходДенег));
                }
            }
            
            /// <summary>
            /// "ПриходДенегL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриходДенегL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриходДенегL", typeof(IIS.Novyjj_proekt_2.ПриходДенег));
                }
            }
        }
    }
}
