//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Novyjj_proekt_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расход приход.
    /// </summary>
    // *** Start programmer edit section *** (РасходПриход CustomAttributes)

    // *** End programmer edit section *** (РасходПриход CustomAttributes)
    public enum РасходПриход
    {
        
        // *** Start programmer edit section *** (РасходПриход.Приход CustomAttributes)

        // *** End programmer edit section *** (РасходПриход.Приход CustomAttributes)
        [Caption("Приход")]
        Приход,
        
        // *** Start programmer edit section *** (РасходПриход.Расход CustomAttributes)

        // *** End programmer edit section *** (РасходПриход.Расход CustomAttributes)
        [Caption("Расход")]
        Расход,
    }
}
