//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Novyjj_proekt_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Регистр оборот.
    /// </summary>
    [Caption("Регистр оборот")]
    [TrimmedStringStorage(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РегистрОборотE", new string[] {
            "ID as \'ID\'",
            "Дата as \'Дата\'",
            "РасходПриход as \'Расход приход\'",
            "Тип as \'Тип\'",
            "Сумма as \'Сумма\'"})]
    [View("РегистрОборотL", new string[] {
            "ID as \'ID\'",
            "Дата as \'Дата\'",
            "РасходПриход as \'Расход приход\'",
            "Тип as \'Тип\'",
            "Сумма as \'Сумма\'"})]
    public class РегистрОборот : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private System.DateTime fДата;
        
        private IIS.Novyjj_proekt_2.РасходПриход fРасходПриход;
        
        private IIS.Novyjj_proekt_2.Тип fТип;
        
        private double fСумма;
        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (РегистрОборот.ID CustomAttributes)

        // *** End programmer edit section *** (РегистрОборот.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (РегистрОборот.ID Get start)

                // *** End programmer edit section *** (РегистрОборот.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (РегистрОборот.ID Get end)

                // *** End programmer edit section *** (РегистрОборот.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрОборот.ID Set start)

                // *** End programmer edit section *** (РегистрОборот.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (РегистрОборот.ID Set end)

                // *** End programmer edit section *** (РегистрОборот.ID Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (РегистрОборот.Дата CustomAttributes)

        // *** End programmer edit section *** (РегистрОборот.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (РегистрОборот.Дата Get start)

                // *** End programmer edit section *** (РегистрОборот.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (РегистрОборот.Дата Get end)

                // *** End programmer edit section *** (РегистрОборот.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрОборот.Дата Set start)

                // *** End programmer edit section *** (РегистрОборот.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (РегистрОборот.Дата Set end)

                // *** End programmer edit section *** (РегистрОборот.Дата Set end)
            }
        }
        
        /// <summary>
        /// РасходПриход.
        /// </summary>
        // *** Start programmer edit section *** (РегистрОборот.РасходПриход CustomAttributes)

        // *** End programmer edit section *** (РегистрОборот.РасходПриход CustomAttributes)
        public virtual IIS.Novyjj_proekt_2.РасходПриход РасходПриход
        {
            get
            {
                // *** Start programmer edit section *** (РегистрОборот.РасходПриход Get start)

                // *** End programmer edit section *** (РегистрОборот.РасходПриход Get start)
                IIS.Novyjj_proekt_2.РасходПриход result = this.fРасходПриход;
                // *** Start programmer edit section *** (РегистрОборот.РасходПриход Get end)

                // *** End programmer edit section *** (РегистрОборот.РасходПриход Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрОборот.РасходПриход Set start)

                // *** End programmer edit section *** (РегистрОборот.РасходПриход Set start)
                this.fРасходПриход = value;
                // *** Start programmer edit section *** (РегистрОборот.РасходПриход Set end)

                // *** End programmer edit section *** (РегистрОборот.РасходПриход Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (РегистрОборот.Сумма CustomAttributes)

        // *** End programmer edit section *** (РегистрОборот.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (РегистрОборот.Сумма Get start)

                // *** End programmer edit section *** (РегистрОборот.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (РегистрОборот.Сумма Get end)

                // *** End programmer edit section *** (РегистрОборот.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрОборот.Сумма Set start)

                // *** End programmer edit section *** (РегистрОборот.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (РегистрОборот.Сумма Set end)

                // *** End programmer edit section *** (РегистрОборот.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (РегистрОборот.Тип CustomAttributes)

        // *** End programmer edit section *** (РегистрОборот.Тип CustomAttributes)
        public virtual IIS.Novyjj_proekt_2.Тип Тип
        {
            get
            {
                // *** Start programmer edit section *** (РегистрОборот.Тип Get start)

                // *** End programmer edit section *** (РегистрОборот.Тип Get start)
                IIS.Novyjj_proekt_2.Тип result = this.fТип;
                // *** Start programmer edit section *** (РегистрОборот.Тип Get end)

                // *** End programmer edit section *** (РегистрОборот.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистрОборот.Тип Set start)

                // *** End programmer edit section *** (РегистрОборот.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (РегистрОборот.Тип Set end)

                // *** End programmer edit section *** (РегистрОборот.Тип Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РегистрОборотE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрОборотE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрОборотE", typeof(IIS.Novyjj_proekt_2.РегистрОборот));
                }
            }
            
            /// <summary>
            /// "РегистрОборотL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистрОборотL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистрОборотL", typeof(IIS.Novyjj_proekt_2.РегистрОборот));
                }
            }
        }
    }
}
