//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Novyjj_proekt_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состав товара.
    /// </summary>
    [Caption("Состав товара")]
    [TrimmedStringStorage(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СоставТовараE", new string[] {
            "Количество as \'Количество\'",
            "Единицы as \'Единицы\'",
            "Материалы as \'Материалы\'",
            "Материалы.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Материалы.Наименование"})]
    [MasterViewDefineAttribute("СоставТовараE", "Материалы", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class СоставТовара : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private IIS.Novyjj_proekt_2.Единицы fЕдиницы;
        
        private IIS.Novyjj_proekt_2.Материалы fМатериалы;
        
        private IIS.Novyjj_proekt_2.Товары fТовары;
        
        /// <summary>
        /// Единицы.
        /// </summary>
        // *** Start programmer edit section *** (СоставТовара.Единицы CustomAttributes)

        // *** End programmer edit section *** (СоставТовара.Единицы CustomAttributes)
        public virtual IIS.Novyjj_proekt_2.Единицы Единицы
        {
            get
            {
                // *** Start programmer edit section *** (СоставТовара.Единицы Get start)

                // *** End programmer edit section *** (СоставТовара.Единицы Get start)
                IIS.Novyjj_proekt_2.Единицы result = this.fЕдиницы;
                // *** Start programmer edit section *** (СоставТовара.Единицы Get end)

                // *** End programmer edit section *** (СоставТовара.Единицы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставТовара.Единицы Set start)

                // *** End programmer edit section *** (СоставТовара.Единицы Set start)
                this.fЕдиницы = value;
                // *** Start programmer edit section *** (СоставТовара.Единицы Set end)

                // *** End programmer edit section *** (СоставТовара.Единицы Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (СоставТовара.Количество CustomAttributes)

        // *** End programmer edit section *** (СоставТовара.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (СоставТовара.Количество Get start)

                // *** End programmer edit section *** (СоставТовара.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (СоставТовара.Количество Get end)

                // *** End programmer edit section *** (СоставТовара.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставТовара.Количество Set start)

                // *** End programmer edit section *** (СоставТовара.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (СоставТовара.Количество Set end)

                // *** End programmer edit section *** (СоставТовара.Количество Set end)
            }
        }
        
        /// <summary>
        /// Состав товара.
        /// </summary>
        [PropertyStorage(new string[] {
                "Материалы"})]
        [NotNull()]
        public virtual IIS.Novyjj_proekt_2.Материалы Материалы
        {
            get
            {
                IIS.Novyjj_proekt_2.Материалы result = this.fМатериалы;
                return result;
            }
            set
            {
                this.fМатериалы = value;
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Novyjj_proekt_2.Товары.
        /// </summary>
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Товары"})]
        public virtual IIS.Novyjj_proekt_2.Товары Товары
        {
            get
            {
                IIS.Novyjj_proekt_2.Товары result = this.fТовары;
                return result;
            }
            set
            {
                this.fТовары = value;
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СоставТовараE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СоставТовараE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СоставТовараE", typeof(IIS.Novyjj_proekt_2.СоставТовара));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СоставТовара.
    /// </summary>
    public class DetailArrayOfСоставТовара : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Novyjj_proekt_2.DetailArrayOfСоставТовара members)

        // *** End programmer edit section *** (IIS.Novyjj_proekt_2.DetailArrayOfСоставТовара members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СоставТовара by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СоставТовара.
        /// </summary>
        public DetailArrayOfСоставТовара(IIS.Novyjj_proekt_2.Товары fТовары) : 
                base(typeof(СоставТовара), ((ICSSoft.STORMNET.DataObject)(fТовары)))
        {
        }
        
        public IIS.Novyjj_proekt_2.СоставТовара this[int index]
        {
            get
            {
                return ((IIS.Novyjj_proekt_2.СоставТовара)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Novyjj_proekt_2.СоставТовара dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
