//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Novyjj_proekt_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип.
    /// </summary>
    // *** Start programmer edit section *** (Тип CustomAttributes)

    // *** End programmer edit section *** (Тип CustomAttributes)
    public enum Тип
    {
        
        // *** Start programmer edit section *** (Тип.1 CustomAttributes)

        // *** End programmer edit section *** (Тип.1 CustomAttributes)
        [Caption("Реализация товаров")]
        1,
        
        // *** Start programmer edit section *** (Тип.2 CustomAttributes)

        // *** End programmer edit section *** (Тип.2 CustomAttributes)
        [Caption("Реализация услуг")]
        2,
        
        // *** Start programmer edit section *** (Тип.3 CustomAttributes)

        // *** End programmer edit section *** (Тип.3 CustomAttributes)
        [Caption("Закупка материалов")]
        3,
    }
}
